/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parus.telas;

/**
 *
 * @author adrieldev
 */
import java.sql.*;
import br.com.parus.dal.ModuloConexao;
import javax.swing.JOptionPane;

public class TelaAviao extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaAviao
     */
    public TelaAviao() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    private void consultar() {
        String sql = "select * from aviao where id=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtAviaoId.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtAviaoModelo.setText(rs.getString(2));
                txtAviaoBagagem.setText(rs.getString(3));
                txtAviaoAssentos.setText(rs.getString(4));
            } else {
                //exibe msg de erro
                JOptionPane.showMessageDialog(null, "Avião não cadastrado");
                //limpar campos
                txtAviaoModelo.setText(null);
                txtAviaoBagagem.setText(null);
                txtAviaoAssentos.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //método para adicionar avião
    private void adicionar() {
        String sql = "insert into aviao(modelo, bagagem, assentos) values(?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtAviaoModelo.getText());
            pst.setString(2, txtAviaoBagagem.getText());
            pst.setString(3, txtAviaoAssentos.getText());

            //adicionar a tabela os dados
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "avião adicionado com sucesso");
                txtAviaoId.setText(null);
                txtAviaoModelo.setText(null);
                txtAviaoAssentos.setText(null);
                txtAviaoBagagem.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    //método para modificar cadastro de aviões
    private void alterar() {
        String sql = "update aviao set modelo=?, bagagem=?, assentos=? where id=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtAviaoModelo.getText());
            pst.setString(2, txtAviaoBagagem.getText());
            pst.setString(3, txtAviaoAssentos.getText());
            pst.setString(4, txtAviaoId.getText());
            //adicionar a tabela os dados
            int modificado = pst.executeUpdate();
            if (modificado > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro modificado com sucesso");
                txtAviaoId.setText(null);
                txtAviaoModelo.setText(null);
                txtAviaoAssentos.setText(null);
                txtAviaoBagagem.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    //método responsável por remover cadastro de um avião
    private void deletar() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este cadastro?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from aviao where id=?";

            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtAviaoId.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Avião removido com sucesso");
                    txtAviaoId.setText(null);
                    txtAviaoModelo.setText(null);
                    txtAviaoAssentos.setText(null);
                    txtAviaoBagagem.setText(null);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtAviaoId = new javax.swing.JTextField();
        txtAviaoModelo = new javax.swing.JTextField();
        txtAviaoAssentos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAviaoCreate = new javax.swing.JButton();
        btnAviaoRead = new javax.swing.JButton();
        btnAviaoUpdate = new javax.swing.JButton();
        btnAviaoDelete = new javax.swing.JButton();
        txtAviaoBagagem = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Avião");
        setPreferredSize(new java.awt.Dimension(350, 350));

        jLabel5.setText("ID (gerado automatiamente) ");

        jLabel6.setText("Modelo");

        jLabel7.setText("Bagagem");

        jLabel8.setText("Assentos");

        btnAviaoCreate.setText("Criar");
        btnAviaoCreate.setToolTipText("Criar");
        btnAviaoCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAviaoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAviaoCreateActionPerformed(evt);
            }
        });

        btnAviaoRead.setText("Procurar");
        btnAviaoRead.setToolTipText("Procurar");
        btnAviaoRead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAviaoRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAviaoReadActionPerformed(evt);
            }
        });

        btnAviaoUpdate.setText("Alterar");
        btnAviaoUpdate.setToolTipText("Alterar");
        btnAviaoUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAviaoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAviaoUpdateActionPerformed(evt);
            }
        });

        btnAviaoDelete.setText("Deletar");
        btnAviaoDelete.setToolTipText("Deletar");
        btnAviaoDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAviaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAviaoDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(txtAviaoId))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAviaoCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAviaoAssentos)
                            .addComponent(txtAviaoBagagem)
                            .addComponent(txtAviaoModelo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAviaoRead)
                                .addGap(18, 18, 18)
                                .addComponent(btnAviaoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAviaoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 39, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAviaoCreate, btnAviaoDelete, btnAviaoRead, btnAviaoUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAviaoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAviaoModelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAviaoBagagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAviaoAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAviaoCreate)
                    .addComponent(btnAviaoRead)
                    .addComponent(btnAviaoUpdate)
                    .addComponent(btnAviaoDelete))
                .addGap(76, 76, 76))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAviaoCreate, btnAviaoDelete, btnAviaoRead, btnAviaoUpdate});

        getAccessibleContext().setAccessibleName("Aviões");

        setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAviaoReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAviaoReadActionPerformed
        consultar();
    }//GEN-LAST:event_btnAviaoReadActionPerformed

    private void btnAviaoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAviaoCreateActionPerformed
        adicionar();
    }//GEN-LAST:event_btnAviaoCreateActionPerformed

    private void btnAviaoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAviaoUpdateActionPerformed
        //chamar método alterar
        alterar();
    }//GEN-LAST:event_btnAviaoUpdateActionPerformed

    private void btnAviaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAviaoDeleteActionPerformed
        deletar();
    }//GEN-LAST:event_btnAviaoDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAviaoCreate;
    private javax.swing.JButton btnAviaoDelete;
    private javax.swing.JButton btnAviaoRead;
    private javax.swing.JButton btnAviaoUpdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAviaoAssentos;
    private javax.swing.JTextField txtAviaoBagagem;
    private javax.swing.JTextField txtAviaoId;
    private javax.swing.JTextField txtAviaoModelo;
    // End of variables declaration//GEN-END:variables
}
