/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parus.telas;

/**
 *
 * @author adrieldev
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usuário = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenCadPessoa = new javax.swing.JMenuItem();
        MenCadAviao = new javax.swing.JMenuItem();
        MenuRelatório = new javax.swing.JMenu();
        MenuRelPessoa = new javax.swing.JMenuItem();
        MenuRelAviao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desafio Parus");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        Desktop.setPreferredSize(new java.awt.Dimension(400, 400));

        btnHome.setText("Início");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/logosplenda-2.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        usuário.setText("user");

        jLabel2.setText("Usuário:");

        MenuCadastro.setText("Cadastro");
        MenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroActionPerformed(evt);
            }
        });

        MenCadPessoa.setText("Pessoa");
        MenCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadPessoaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenCadPessoa);

        MenCadAviao.setText("Avião");
        MenCadAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadAviaoActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenCadAviao);

        jMenuBar1.add(MenuCadastro);

        MenuRelatório.setText("Relatório");

        MenuRelPessoa.setText("Listar Voos");
        MenuRelPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelPessoaActionPerformed(evt);
            }
        });
        MenuRelatório.add(MenuRelPessoa);

        MenuRelAviao.setText("Listar Aviões");
        MenuRelAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelAviaoActionPerformed(evt);
            }
        });
        MenuRelatório.add(MenuRelAviao);

        jMenuBar1.add(MenuRelatório);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuário, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHome))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usuário, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );

        setSize(new java.awt.Dimension(583, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnHomeActionPerformed

    private void MenCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadPessoaActionPerformed
        //abrir abaixo o form TelaPessoa
        TelaPessoa pessoa = new TelaPessoa();
        pessoa.setVisible(true);
        Desktop.add(pessoa);
    }//GEN-LAST:event_MenCadPessoaActionPerformed

    private void MenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadastroActionPerformed

    private void MenCadAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadAviaoActionPerformed
        TelaAviao Aviao = new TelaAviao();
        Aviao.setVisible(true);
        Desktop.add(Aviao);
    }//GEN-LAST:event_MenCadAviaoActionPerformed

    private void MenuRelAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelAviaoActionPerformed
        TelaRelAviões RelAviao = new TelaRelAviões();
        RelAviao.setVisible(true);
        Desktop.add(RelAviao);
    }//GEN-LAST:event_MenuRelAviaoActionPerformed

    private void MenuRelPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelPessoaActionPerformed
        TelaRelVoos RelVoos = new TelaRelVoos();
        RelVoos.setVisible(true);
        Desktop.add(RelVoos);
    }//GEN-LAST:event_MenuRelPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MenCadAviao;
    private javax.swing.JMenuItem MenCadPessoa;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuRelAviao;
    private javax.swing.JMenuItem MenuRelPessoa;
    private javax.swing.JMenu MenuRelatório;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel usuário;
    // End of variables declaration//GEN-END:variables
}
