/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parus.telas;

/**
 *
 * @author adrieldev
 */
import java.sql.*;
import br.com.parus.dal.ModuloConexao;
import javax.swing.JOptionPane;

public class TelaPessoa extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPessoa
     */
    public TelaPessoa() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    private void consultar() {
        String sql = "select * from pessoa where cpf=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPessoaCpf.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtPessoaNome.setText(rs.getString(2));
                cboPessoaSituacao.setSelectedItem(rs.getString(3));
                txtPessoaAviao.setText(rs.getString(4));
            } else {
                //exibe msg de erro
                JOptionPane.showMessageDialog(null, "Pessoa não cadastrada");
                //limpar campos
                txtPessoaNome.setText(null);
                txtPessoaAviao.setText(null);
                cboPessoaSituacao.setSelectedItem(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //método para adicionar usuários
    private void adicionar() {
        String sql = "insert into pessoa(cpf, nome, situacao, aviao) values(?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPessoaCpf.getText());
            pst.setString(2, txtPessoaNome.getText());
            pst.setString(3, cboPessoaSituacao.getSelectedItem().toString());
            pst.setString(4, txtPessoaAviao.getText());

            //adicionar a tabela os dados
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "usuário adicionado com sucesso");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtPessoaCpf = new javax.swing.JTextField();
        txtPessoaNome = new javax.swing.JTextField();
        txtPessoaAviao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboPessoaSituacao = new javax.swing.JComboBox<>();
        btnPessoaCreate = new javax.swing.JButton();
        btnPessoaRead = new javax.swing.JButton();
        btnPessoaUpdate = new javax.swing.JButton();
        btnPessoaDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pessoas");
        setPreferredSize(new java.awt.Dimension(350, 350));

        jLabel5.setText("CPF");

        jLabel6.setText("Nome");

        jLabel7.setText("Situação");

        jLabel8.setText("Avião");

        cboPessoaSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piloto", "Co-piloto", "Comissário", "Passageiro" }));
        cboPessoaSituacao.setToolTipText("Piloto\nCo-piloto\nComissário\nPassageiro");
        cboPessoaSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPessoaSituacaoActionPerformed(evt);
            }
        });

        btnPessoaCreate.setText("Criar");
        btnPessoaCreate.setToolTipText("Criar");
        btnPessoaCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPessoaCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaCreateActionPerformed(evt);
            }
        });

        btnPessoaRead.setText("Procurar");
        btnPessoaRead.setToolTipText("Procurar");
        btnPessoaRead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPessoaRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaReadActionPerformed(evt);
            }
        });

        btnPessoaUpdate.setText("Alterar");
        btnPessoaUpdate.setToolTipText("Alterar");
        btnPessoaUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPessoaDelete.setText("Deletar");
        btnPessoaDelete.setToolTipText("Deletar");
        btnPessoaDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPessoaNome)
                            .addComponent(txtPessoaCpf)
                            .addComponent(txtPessoaAviao)
                            .addComponent(cboPessoaSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPessoaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPessoaRead)
                        .addGap(18, 18, 18)
                        .addComponent(btnPessoaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPessoaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPessoaCreate, btnPessoaDelete, btnPessoaRead, btnPessoaUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPessoaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPessoaNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPessoaSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPessoaAviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPessoaCreate)
                    .addComponent(btnPessoaRead)
                    .addComponent(btnPessoaUpdate)
                    .addComponent(btnPessoaDelete))
                .addGap(76, 76, 76))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPessoaCreate, btnPessoaDelete, btnPessoaRead, btnPessoaUpdate});

        cboPessoaSituacao.getAccessibleContext().setAccessibleDescription("Piloto\nCo-piloto\nComissário\nPassageiro");

        setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void cboPessoaSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPessoaSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPessoaSituacaoActionPerformed

    private void btnPessoaReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaReadActionPerformed
        consultar();
    }//GEN-LAST:event_btnPessoaReadActionPerformed

    private void btnPessoaCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaCreateActionPerformed
        adicionar();
    }//GEN-LAST:event_btnPessoaCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPessoaCreate;
    private javax.swing.JButton btnPessoaDelete;
    private javax.swing.JButton btnPessoaRead;
    private javax.swing.JButton btnPessoaUpdate;
    private javax.swing.JComboBox<String> cboPessoaSituacao;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtPessoaAviao;
    private javax.swing.JTextField txtPessoaCpf;
    private javax.swing.JTextField txtPessoaNome;
    // End of variables declaration//GEN-END:variables
}
