/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parus.telas;

/**
 *
 * @author adrieldev
 */
import java.sql.*;
import br.com.parus.dal.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class TelaRelAviões extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaAviao
     */
    public TelaRelAviões() {
        initComponents();
        conexao = ModuloConexao.conector();
        pesquisar_aviao();

    }

    //pesquisar todos aviões
    private void pesquisar_aviao() {
        String sql = "select * from aviao";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            tblAvioes.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelAviões = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvioes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Avião");
        setPreferredSize(new java.awt.Dimension(350, 350));

        btnRelAviões.setText("Atualizar Lista");
        btnRelAviões.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelAviõesActionPerformed(evt);
            }
        });

        tblAvioes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAvioes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRelAviões)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnRelAviões)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Aviões");

        setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelAviõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelAviõesActionPerformed
        pesquisar_aviao();
    }//GEN-LAST:event_btnRelAviõesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelAviões;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAvioes;
    // End of variables declaration//GEN-END:variables
}
