/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parus.telas;

/**
 *
 * @author adrieldev
 */
import java.sql.*;
import br.com.parus.dal.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class TelaRelVoos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaAviao
     */
    public TelaRelVoos() {
        initComponents();
        conexao = ModuloConexao.conector();
        pesquisar_voo();

    }

    //pesquisar todos aviões
    private void pesquisar_voo() {
        String sql = "select * from pessoa where aviao=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtRelId.getText());
            rs = pst.executeQuery();
            tblVoos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelVoos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtRelId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Avião");
        setPreferredSize(new java.awt.Dimension(350, 350));

        btnRelVoos.setText("Listar Passageiros");
        btnRelVoos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelVoosActionPerformed(evt);
            }
        });

        tblVoos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Modelo", "Bagagem", "Assentos"
            }
        ));
        jScrollPane1.setViewportView(tblVoos);

        jLabel1.setText("Id do Avião");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRelVoos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtRelId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(btnRelVoos)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Aviões");

        setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelVoosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelVoosActionPerformed
        pesquisar_voo();
    }//GEN-LAST:event_btnRelVoosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelVoos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVoos;
    private javax.swing.JTextField txtRelId;
    // End of variables declaration//GEN-END:variables
}
